### ISSUE TITLE
exporting workflow fail

### ISSUE THREAD

**Issue by Bbertatum** [coldsource/evqueue-frontend-php#2]
Hi,

I can choose any of my workflows and get this error when I try to export :  

`[Sun Jan 14 22:31:25.489254 2018] [:error] [pid 40340] [client 89.234.156.85:56482] PHP Notice:  Undefined variable: evqueue in /usr/share/evqueue/export.php on line 11, referer: https://evqueue.mydomain.fr/evqueue/workflow.php
[Sun Jan 14 22:31:25.489335 2018] [:error] [pid 40340] [client 89.234.156.85:56482] PHP Fatal error:  Uncaught Error: Call to a member function Api() on null in /usr/share/evqueue/export.php:11\nStack trace:\n#0 {main}\n  thrown in /usr/share/evqueue/export.php on line 11, referer: https://evqueue.mydomain.fr/evqueue/workflow.php`

**Comment by coldsource** [comment]
I Bbertatum,

I juste fixed this on master branch. See this commit :
https://github.com/coldsource/evqueue-frontend-php/commit/b1ea7954758e94e4636b0bbd42dc6d19a806b2f6

Please tell me if everything is working now.
