### ISSUE TITLE
PHP7.2 - Update Dependencies

### ISSUE THREAD

**Issue by kyleamadio** [coldsource/evqueue-frontend-php#3]
Hi Could you possibly update the dependencies for PHP7.2

Package: evqueue-frontend-php
Version: 2.0
Architecture: all
Maintainer: Thibault Kummer <bob@coldsource.net>
Installed-Size: 3551
Depends: apache2, **libapache2-mod-php7.0, php7.0-mysql, php7.0-xsl, php7.0-zip, php7.0-xml**
Section: net
Priority: optional
Homepage: http://www.evqueue.net
Description: evQueue web board
 evQueue web interface: simply create and run workflows

**Comment by coldsource** [comment]
Hi,

Sure it's possible. Which distro are you packaging for ? I had set this for debian 9.

**Comment by kyleamadio** [comment]
Hi Ubuntu 18.04.1 AMD64

**Comment by kyleamadio** [comment]
Btw thanks for doing this. I installed a debian 9 container and it works nicely.

**Comment by coldsource** [comment]
Ok great. Anyhow I will see if I can provide package generation for multiple distro.

Thanks for your feedback.

**Comment by kyleamadio** [comment]
If you do there are some dependencies that i had to install manually. Ill send the details to you shortly.
