### ISSUE TITLE
Unknown command or action

### ISSUE THREAD

**Issue by wellingtonssilva-leishman** [coldsource/evqueue-frontend-php#4]
Hello,

After upgrade my evqueue-core to version 2.1, and upgraded the frontend to current release, when entering on System State > Workflows instances (index.php), it shows 2 alert messages with same text "evQueue error returned from engine: Unknown command or action".

Apparently it occurs when it call get-nodes.php and list-instances.php?status=executing, but even with this alerts, the interface seems to be ok, but I don't know i fon backend something happens.

**Comment by coldsource** [comment]
Hi thanks for the report. It seems we have forgotten to tag the release 2.1 on frontend. So latest version is not fully compatible with 2.1 engine.

We are currently working on 2.2 release (works in production). So you can upgrade everything to latest version. If you prefer I can also add 2.1 tag on frontend so you have a compatible version.

Please let me know what you want to do.

Best regards

**Comment by wellingtonssilva-leishman** [comment]
Hello,

I upgraded everything to the latest version, it worked.

Thank you.
